main:main.cpp
gcc -L/usr/lib -o main main.cpp -lE101

# Use this file to facilitate the compilation of the code. For it to work, a copy of
# LibE101.so must be in /usr/lib/ — you can get one here: https://github.com/kaiwhata/ENGR101-2017
# 
# The -L option specifies the location of the library and -l specifies the library name.
# The -Wall option can be added to show all warnings during compilation.
# 
# If you want to include math functions, use "#include math.h" in the program and change the
# gcc command to include the -lm flag. (-lm stands for link math libraries)